name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run the Docker image
      run: docker build -t exercice .
    - name: Run Docker container
      run: docker run --rm -ti --name execution_exo exercice
